name: lint
on:
  push:
    tags:
      - v*
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: .
